spring.application.name=MediGO

# Database (cambiar a spring.jpa.hibernate.ddl-auto=create-drop si se quiere que se borre)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.deserialization.fail-on-unknown-properties=true
jwt.secret=${JWT_SECRET}
jwt.expiration-access=${JWT_EXPIRATION_ACCESS}
jwt.expiration-refresh=${JWT_EXPIRATION_REFRESH}

# GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_SMPT_USERNAME}
spring.mail.password=${MAIL_SMPT_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MediGO
app.name=MediGO
app.frontend-url=http://localhost:3000

# Stripe Configuration
stripe.api.secret-key=${STRIPE_API_SECRET_KEY}
stripe.platform.commission=0.05
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# VIDEO
whereby.api.key=${WHEREBY_API_KEY}
whereby.api.url=https://api.whereby.dev/v1

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}

# Para el load balancer
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always